---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "ns-list"
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nancy
subjects:
  - kind: User
    name: nancy
roleRef:
  kind: ClusterRole
  name: ns-list
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ned
subjects:
  - kind: User
    name: ned
roleRef:
  kind: ClusterRole
  name: ns-list
  apiGroup: rbac.authorization.k8s.io